language: java
notifications:
  slack:
    secure: zmCPujBaE/We6q3Bm3NRH/CSD1Y8vss9Bz05V8fF2qPr3GGuA4IkmOKvrrWiVzRH8ZlnKhAttHVzTL3U63KWEcoMSBLutTtZZ7WckY0/7P/33sPhTN8sWr66JQfAcAf6DX/SL5JIJKhyBCK8KJ4o18Nw0MuXmDlZEgYhPA0ahTqoABKrY+Hn4VgUyO7Nfq/ysAs3FZUzpxbNKz2tdKrSDdZobyfU2Y3d9uPJHWysOvmEwV32OWYO8tjjUB5CA+0ydGbibEBznrUFuhugUGSib1Gp8/Un4aNglQNCvypDZw6jl26P0zcR/E7KOHQbAnGwLqD4lGbkc1bSeBE7jU7lDISnxVG/9PlWAQjggC2oFJ4d8XV22OglFgF8eRQD402XcA8NsX7Jrmpe7RtvwIeLrQrohiNvkqwq/C8WplyABvgj8g87tTh5sml0ypm49lJa4YaW9HjHxdmMpU/Rg97gGFfTsQofRvYq7y9bzRSGT1O/T15lpu61K88N3d0IyUjdB02g7IEHva8bY4FzVDbNuFFSzK6UpqvUr6TaMwQQtxqwTxyo0pe2PgpkYfARKmrZMxAq9bensGBfJaeMWuqnWTKLVAoMe5f+QpVyZyq8ZI8UFOpjfa5csN/cnmKhYUXoN1NYSyXgaErdG2svQBzuaHTQatfnOQrjq5Xn4qMYz+E=
addons:
  sonarcloud:
    organization: davidwpowell-github
    token: $SONAR_TOKEN
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: frozen-lake-89585
  on:
    repo: davidwpowell/rest-service
